name: Your New Jekyll Site
baseurl: "/"
url: "https://aifit.github.io/yjame"
markdown: redcarpet
highlighter: null # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:title/
