name: Yahya J. Aifit
baseurl: "/"
# url: "http://localhost:3000"
url: "https://aifit.github.io/yjame"
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:title/
markdown: kramdown
title: Yahya J. Aifit
description: "Portfolio and Blog of Yahya J Aifit, Front-end Web Developer living and working in Jakarta Indonesia. Focusing on simple and minimalist design."
tracking_id: "UA-52996034-4"
plugins:
  - jekyll-feed
