# Global
name: Yahya J. Aifit
baseurl: "/"
# url: "http://localhost:3000"
url: "https://yja.me"
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:categories/:title/
markdown: kramdown
title: Yahya J. Aifit
description: "Portfolio dan Blog dari Yahya J Aifit seorang Front-end Web Developer"

# Google Analitycs
tracking_id: "UA-52996034-4"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-target-blank
