name: Your New Jekyll Site
baseurl: "/"
# url: "https://aifit.github.io/yjame/"
url: http://localhost:3000
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
